exchange:
  api:
    base-url: "https://api.apilayer.com/exchangerates_data"
    api-key: KQ7o2u5nhwiDtGeEvrj5ccS4NNAhOp7w
    all-currencies-endpoint: /v1/latest
    symbols-endpoint: /symbols
    historical-endpoint: /v1
    convert-endpoint: /convert
feign:
  client:
    config:
      default:
        defaultRequestHeaders:
#          Authorization:
#            - Basic dXNlcjpwYXNzd29yZA==a
          apikey:
            - KQ7o2u5nhwiDtGeEvrj5ccS4NNAhOp7w